# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date
    - name: Python Syntax Checker
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

 
  windows:
    runs-on: windows-latest
    steps:
    - run: date
  macos:
    runs-on: macos-latest
    steps:
    - run: date

  last:
    needs: [windows, macos, ubuntu]
    runs-on: Windows-latest
    steps:
    - run: date
 
